name: autzone_client
description: Civil rights social platform - web client
dependencies:
  dquery: any
  js: any
  angel_serialize: ^2.0.0
  autzone_models:
    path: ../autzone_models
dev_dependencies:
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers: '>=2.12.0-dev.1 <3.0.0'
homepage: http://www.divergentlabs.org
