# TEMPLATE - INCOMPLETE! To use this: (1) copy it to config.yaml, (2) add the credentials for amazon
# and the database where it has the word USER_HERE and PASSWORD_HERE below, (3) remove this comment

dev: "Y" #Y or N = developer mode (affects which config entries are used)
homeUrl: "https://www.autistic.zone"
linkbackUrl: "https://www.autistic.zone"
domain: "www.autistic.zone" #domain name for SSL binding
siteName: "Autistic Zone"
amazonS3: #credentials for S3
  id: "USER_HERE"
  key: "PASSWORD_HERE"
  endpoint: "https://s3-us-west-2.amazonaws.com"
amazonS3Avatar: #images defined in xuser.avatar_no
  bucket: "autisticzoneavatar"
  url: "http://autisticzoneavatar.s3-website-us-west-2.amazonaws.com/" #root of public url for graphics in the bucket, with final /
amazonS3Post: #images defined in conv_post
  bucket: "autisticzonepost"
  url: "http://autisticzonepost.s3-website-us-west-2.amazonaws.com/" #root of public url for graphics in the bucket, with final /
smtp:
  host: "email-smtp.us-west-2.amazonaws.com"
  port: 587 #465, 25, 587, 2587
  user: "USER_HERE"
  password: "PASSWORD_HERE"
  from: "star@divergentlabs.org" #amazon SES only works with preverified senders
database:
  host: autistic.zone
  port: 5432
  dbname: autzone
  user: postgres
  password:
database_dev:
  host: localhost
  port: 5432
  dbname: autzone
  user: star
  password:
