name: models
description: Civil rights social platform - 2 tier models
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  angel_framework: ^2.0.0-alpha #https://angel-dart.gitbook.io/angel/v/2.x/guides/without-the-boilerplate
  angel_model: ^1.0.0
  angel_serialize: ^2.0.0
dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
  angel_serialize_generator: ^2.0.0
homepage: http://www.divergentlabs.org
